fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User

    from_email:
        address: '%env(MAILER_FROM)%'
        sender_name: '%env(MAILER_FROM_NAME)%'

    registration:
        confirmation:
            enabled: true


