twig:
    paths: ['%kernel.project_dir%/templates', '%kernel.project_dir%/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - 'bootstrap_3_layout.html.twig'

    globals:
        ordersService: '@App\Service\Orders'
